/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ComplexToPacked12.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(06b0845a9c21691b9b52b5b5ead74eab)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <compress/ComplexToPacked12.h>
// pydoc.h is automatically generated in the build directory
#include <ComplexToPacked12_pydoc.h>

void bind_ComplexToPacked12(py::module& m)
{

    using ComplexToPacked12    = ::gr::compress::ComplexToPacked12;


    py::class_<ComplexToPacked12, gr::sync_interpolator,
        std::shared_ptr<ComplexToPacked12>>(m, "ComplexToPacked12", D(ComplexToPacked12))

        .def(py::init(&ComplexToPacked12::make),
           D(ComplexToPacked12,make)
        )
        



        ;




}








