/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(CompressedMsgToStream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(47bc13712778176844a989f7eb360da3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <compress/CompressedMsgToStream.h>
// pydoc.h is automatically generated in the build directory
#include <CompressedMsgToStream_pydoc.h>

void bind_CompressedMsgToStream(py::module& m)
{

    using CompressedMsgToStream    = ::gr::compress::CompressedMsgToStream;


    py::class_<CompressedMsgToStream, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<CompressedMsgToStream>>(m, "CompressedMsgToStream", D(CompressedMsgToStream))

        .def(py::init(&CompressedMsgToStream::make),
           D(CompressedMsgToStream,make)
        )
        



        ;




}








