/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(compress.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(308c965e58bb112169459def815eaa23)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <compress/compress.h>
// pydoc.h is automatically generated in the build directory
#include <compress_pydoc.h>

void bind_compress(py::module& m)
{

    using compress    = ::gr::compress::compress;


    py::class_<compress, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<compress>>(m, "compress", D(compress))

        .def(py::init(&compress::make),
           py::arg("itemsize"),
           py::arg("compressionBlockSize"),
           py::arg("numThreads"),
           py::arg("addHeader"),
           py::arg("verbose"),
           D(compress,make)
        )
        



        ;




}








