/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(CompressedFileSink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5ea8be5858d852b3f451f1e06facdabf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <compress/CompressedFileSink.h>
// pydoc.h is automatically generated in the build directory
#include <CompressedFileSink_pydoc.h>

void bind_CompressedFileSink(py::module& m)
{

    using CompressedFileSink    = ::gr::compress::CompressedFileSink;


    py::class_<CompressedFileSink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<CompressedFileSink>>(m, "CompressedFileSink", D(CompressedFileSink))

        .def(py::init(&CompressedFileSink::make),
           py::arg("itemsize"),
           py::arg("filename"),
           py::arg("unbuffered"),
           py::arg("append") = false,
           D(CompressedFileSink,make)
        )
        



        ;




}








