/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Packed12ToComplex.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(12a7ef1bdabc4a5b359a3ea199ce451c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <compress/Packed12ToComplex.h>
// pydoc.h is automatically generated in the build directory
#include <Packed12ToComplex_pydoc.h>

void bind_Packed12ToComplex(py::module& m)
{

    using Packed12ToComplex    = ::gr::compress::Packed12ToComplex;


    py::class_<Packed12ToComplex, gr::sync_decimator,
        std::shared_ptr<Packed12ToComplex>>(m, "Packed12ToComplex", D(Packed12ToComplex))

        .def(py::init(&Packed12ToComplex::make),
           D(Packed12ToComplex,make)
        )
        



        ;




}








