/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(StreamToDecompressionMsg.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bb6887a774484153f0d94b030c525052)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <compress/StreamToDecompressionMsg.h>
// pydoc.h is automatically generated in the build directory
#include <StreamToDecompressionMsg_pydoc.h>

void bind_StreamToDecompressionMsg(py::module& m)
{

    using StreamToDecompressionMsg    = ::gr::compress::StreamToDecompressionMsg;


    py::class_<StreamToDecompressionMsg, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<StreamToDecompressionMsg>>(m, "StreamToDecompressionMsg", D(StreamToDecompressionMsg))

        .def(py::init(&StreamToDecompressionMsg::make),
           D(StreamToDecompressionMsg,make)
        )
        



        ;




}








